CREATE MEMORY TABLE if not exists "USER_DETAIL"
(
    "USER_ID"    UUID NOT NULL,
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME"  CHARACTER VARYING(255),
    "LOGIN"      CHARACTER VARYING(255)
);